### ISSUE TITLE
multiple versions support

### ISSUE THREAD

**Issue by keradus** [sebastianbergmann/phpunit-documentation-english#10]
Hi

Is it planned to have **new** docs not only for newest version, but also for older ones ?
Like, even when having phpunit 6, there are a lot of ppl still using v4

**Comment by sebastianbergmann** [comment]
The old documentation is still available, for instance at

* https://phpunit.de/manual/4.8/en/index.html
* https://phpunit.de/manual/5.7/en/index.html
* https://phpunit.de/manual/6.5/en/index.html

Starting with PHPUnit 7.0, the documentation is hosted on ReadTheDocs. There it will be versioned for 7.0, 7.1, etc.

**Comment by keradus** [comment]
awesome that old docs won't be dropped ;)
yet, i do find my question still valid - how to contribute to apply changes for, for example, version 7.0 + vs 7.1 + ?

also, maybe some contributing guidelines would be fine to write it down once, also mentioning how to contribute to 7+ (this repo) and 4-6 (old repo) ?

**Comment by keradus** [comment]
Ha, basically I see you created TODO to write it down, thanks !
ref #11
