### ISSUE TITLE
ReadTheDocs.io issues

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-documentation-english#102]
* On https://phpunit.readthedocs.io/en/7.2/installation.html it reads "You are not using the most up to date version of the library. 7.3 is the newest version." but PHPUnit 7.4 is the newest version
* On https://phpunit.readthedocs.io/en/7.3/installation.html the `|version|` placeholder is not replaced

**Comment by sebastianbergmann** [comment]
@sebastianheuer Can you have a look? Thanks!

**Comment by sebastianheuer** [comment]
The first issue is "fixed". Version 7.4 was not marked as active on https://readthedocs.org/dashboard/phpunit/versions/

I also switched the default version to 7.4. 

The second issue is not related to 7.3, this probably happens because the placeholder is in a code block. I will have a look.

**Comment by sebastianbergmann** [comment]
Until now, I did not even see 7.4 as a version there. Strange. Thanks!

**Comment by nelson6e65** [comment]
In translated docs, there is no replacement for `|version|` placeholders at all.

**Comment by Xerkus** [comment]
@sebastianbergmann @sebastianheuer related: 7.4 is shown as latest on readthedocs. No 7.5 or latest 8.0

**Comment by sebastianbergmann** [comment]
https://phpunit.readthedocs.io/en/7.2/installation.html has "You are not reading the most recent version of this documentation. 8.0 is the latest version available.".
