### ISSUE TITLE
mapTestClassNameToCoveredClassName attribute in older versions and other languages

### ISSUE THREAD

**Issue by arneschuldt** [sebastianbergmann/phpunit-documentation-english#105]
My pull request https://github.com/sebastianbergmann/phpunit-documentation-english/pull/104 is probably also relevant for older versions:

Unfortunately, I am unable to judge which versions are affected because it actually references the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage/commit/25cc3d16d7f6dc2d90f125594515256ec29962fa) project.

Furthermore, also the other languages might be affected since the respective version.

**Comment by sebastianbergmann** [comment]
See https://github.com/sebastianbergmann/phpunit-documentation-english/pull/104#issuecomment-433309674
