### ISSUE TITLE
How to deal with deprecated features in the documentation

### ISSUE THREAD

**Issue by daveh** [sebastianbergmann/phpunit-documentation-english#119]
Is there a standard for updating the documentation for dealing with deprecated features?

For example, with the release of PHPUnit 8, annotations for expecting exceptions have been deprecated. Should the [documentation about these](https://phpunit.readthedocs.io/en/8.0/writing-tests-for-phpunit.html#testing-exceptions) simply be removed, or marked as deprecated then removed in the documentation for PHPUnit 9 (when they will actually be removed)?

**Comment by sebastianbergmann** [comment]
Yes, the documentation for deprecated functionality should just be removed. Thanks!
