### ISSUE TITLE
Extend the result examples in the doc of logging with skip and incomplete 

### ISSUE THREAD

**Issue by SimonHeimberg** [sebastianbergmann/phpunit-documentation-english#12]
In [logging.rst](https://github.com/sebastianbergmann/phpunit-documentation-english/blob/c11e6ea/src/logging.rst) there is an example for junit log format showing `pass`, `failure `and `error`.
Could this please be extended to also show `skip` and `ignore`?

BTW, do we not want to inclde examples for the teamcity format (--log-teamcity)?

Updated from https://github.com/sebastianbergmann/phpunit-documentation/issues/348

**Comment by keradus** [comment]
@SimonHeimberg , why not.
could you please send a PR ?
