### ISSUE TITLE
Document assertions instroduced in PHPUnit 7.5

### ISSUE THREAD

**Issue by borys-p** [sebastianbergmann/phpunit-documentation-english#126]
The code emits a warning when `assertContains` is used with strings: `Using assertContains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertStringContainsString() or assertStringContainsStringIgnoringCase() instead.` but `assertStringContainsString()` and its siblings are not documented.

**Comment by sebastianbergmann** [comment]
The following assertions that were introduced in PHPUnit 7.5 need to be documented:
* `assertEqualsCanonicalizing()`
* `assertEqualsIgnoringCase()`
* `assertEqualsWithDelta()`
* `assertNotEqualsCanonicalizing()`
* `assertNotEqualsIgnoringCase()`
* `assertNotEqualsWithDelta()`
* `assertStringContainsString()`
* `assertStringContainsStringIgnoringCase()`
* `assertStringNotContainsString()`
* `assertStringNotContainsStringIgnoringCase()`
