### ISSUE TITLE
"Edit on GitHub" link broken

### ISSUE THREAD

**Issue by oliverklee** [sebastianbergmann/phpunit-documentation-english#128]
This issue probably is related to #41 (i.e., it probably blocks it).

Steps to reproduce:

1. go to https://phpunit.readthedocs.io/en/8.0/ (which is the English version of the docs)
2. at the bottom of the left sidebar, select any of the following branches: 7.1., 7.2., 7.3., 7.4, 7.5, 8.0
3. click on the "Edit on GitHub" link at the top of the page

Expected results:
The corresponding file on GitHub, and a URL like this:
`https://github.com/sebastianbergmann/phpunit-documentation-english/blob/7.0/src/index.rst`

Actual results:
A page that has the text "Not found" on it, and a URL like this:
`https://github.com/sebastianbergmann/phpunit-documentation-english//7.1/src/index.rst`

Apart from the different version number, the most striking difference seems to be that the broken URLs are missing the "blob" segment. Adding that segment to the broken URL makes it work fine.

With version 7.0, the Edit link is fine. Starting with 7.1, the problem occurs.

**Comment by sebastianbergmann** [comment]
Looks like https://github.com/rtfd/readthedocs.org/issues/5303 to me.

**Comment by oliverklee** [comment]
Does this mean this will be fixed automatically the next time the docs are published?

**Comment by sebastianbergmann** [comment]
I hope so.
