### ISSUE TITLE
Add missing documentation for "@depends shallowclone <method>"

### ISSUE THREAD

**Issue by reinholdfuereder** [sebastianbergmann/phpunit-documentation-english#14]
(Re-created for https://github.com/sebastianbergmann/phpunit-documentation/issues/492)

This was added in: sebastianbergmann/phpunit#2496

**Comment by keradus** [comment]
Hi @reinholdfuereder ,
could you please raise a PR for it ? With new way of docs, it's so easier ;)
Thanks !

**Comment by reinholdfuereder** [comment]
I'll try...

Can it be that some (?) of the code examples are still taken from the old archived phpunit-documentation project? Because I thought about updating "Example 2.4 Test with multiple dependencies" (http://phpunit.readthedocs.io/en/latest/writing-tests-for-phpunit.html#writing-tests-for-phpunit-examples-multipledependencies-php) in the way of "https://github.com/sebastianbergmann/phpunit/blob/master/tests/_files/MultiDependencyTest.php", i.e. explicitly declaring test method arguments... (to reduce the magic)

**Comment by keradus** [comment]
sure it can :)
