### ISSUE TITLE
PHPUnit manual command line options "--report-useless-tests" vs. "--dont-report-useless-tests"

### ISSUE THREAD

**Issue by reinholdfuereder** [sebastianbergmann/phpunit-documentation-english#15]
(Re-created for sebastianbergmann/phpunit-documentation#424)

(This is of course just a minor issue...)

See https://phpunit.de/manual/current/en/textui.html#textui.clioptions

At the top it correctly mentions the new option:
> Test Execution Options:
> `--dont-report-useless-tests` Do not report tests that do not test anything.

But further down it then explains the old option:
> `--report-useless-tests`
> Be strict about tests that do not test anything. See Chapter 6 for details.

Ad comment from @farwish (from 4 April 2017):
> The manual may be older, we should see command line.

=> This issue is really only about the minor inconsistency issue in the documentation; the CLI shows:
>   --dont-report-useless-tests Do not report tests that do not test anything.

**Comment by keradus** [comment]
Hi, looks like quite a nice thing to fix, even if small. Could you help and send a PR for it please? Thanks !

**Comment by keradus** [comment]
Thanks for the PR !
As it's already merged, I do think we could close this issue now ;)

**Comment by reinholdfuereder** [comment]
@keradus OK for me; we don't have to be so picky...
