### ISSUE TITLE
Document configuration options related execution order

### ISSUE THREAD

**Issue by Bilge** [sebastianbergmann/phpunit-documentation-english#173]
First, the only mention of a feature governing the execution order of tests is in an [appendix page](https://phpunit.readthedocs.io/en/8.4/configuration.html), which provides poor exposure to a major feature.

Next, the only thing the docs have to say about the `executionOrder` flag is that, *This attribute configures the order in which tests are executed.* This is clearly not enough to explain a feature that currently has no less than eight different configuration values and accepts multiple values thereof.

Specifically, as a user I want to know: 

* What does `defects` do?
* What does `depends`/`no-depends` do?
* Assuming `duration` orders tests by duration, how does PHPUnit know how long my tests take, to produce that ordering?
* I know from discussion with other developers that there is more than meets the eye to `random`, specifically that seed values can be provided. If true, this must be documented.
* What does `size` do? How does PHPUnit know the "size"?
* In which version was this feature, and the respective settings, added?

**Comment by clement-fleury-assoconnect** [comment]
🆙 on this issue ;)

**Comment by AllenJB** [comment]
The documentation indicates that combinations are possible, using ',' as a separator (without specifying limitations), but when you choose certain (or rather, other than a certain list) of combinations, you get a warning that this is not valid, but no reasoning as to why.

In my case I was trying to use "defects,random" (using PHPUnit 9.1.1), which I take to mean "run defective tests from last run first, then run everything else in random order".

**Comment by amcsi** [comment]
I was trying to change how tests were sorted when I noticed that it didn't seem to work.
I found this issue, but this seemed to be about the docs.
Although what each order flag does is indeed not well documented, I believe that regardless, there's a bug that makes them not work in any way. Please see the issue I've opened: sebastianbergmann/phpunit#4619

**Comment by Bilge** [comment]
Any year now...

**Comment by localheinz** [comment]
Fixed with #308.
