### ISSUE TITLE
PHP Configuration

### ISSUE THREAD

**Issue by BackEndTea** [sebastianbergmann/phpunit-documentation-english#174]
Recently i ran into an issue where phpunit exited, without any message about what happened.

After some googling i ran into an article that said to run phpunit as follows:
```
$ php -d display_errors=On vendor/bin/phpunit
```

And then it turned out someone extended a class and made a non static method static, resulting in a fatal error. I had kinda expected phpunit to set `display_errors` by default, but it doesn't. For now i have opted to add it to the phpunit.xml.

Would it be an idea to configure this ini setting by default when running phpunit?

**Comment by sebastianbergmann** [comment]
The documentation should suggest these settings

* `memory_limit=-1`
* `error_reporting=-1`
* `log_errors_max_len=0`
* `zend.assertions=1`
* `assert.exception=1`
* `xdebug.show_exception_trace=0`

I do not think, however, that PHPUnit should "enforce" them.
