### ISSUE TITLE
Please include the PHPUnit changelog in the documentation

### ISSUE THREAD

**Issue by jdufresne** [sebastianbergmann/phpunit-documentation-english#177]
It would be great if the PHPUnit documentation included the changelog as far back as possible.

I was recently trying to understand when a feature was introduced, but it looks like the changelogs were intentionally deleted: https://github.com/sebastianbergmann/phpunit/commit/ce4de31b6bcc5b2ff2774e599b0a0d59b08d7292

I wasn't able to easily find an archive of these deleted changelogs. Because the changelogs had been deleted, I had to use the git history to find the introduction of the feature.

These historical changelogs are useful to use as a reference when a package is discussing and deciding what version of PHP and PHPUnit to support.

Many other software packages keep their old changelogs around. For example, here is the changelog for the very old PHP 4 releases: https://www.php.net/ChangeLog-4.php

Thanks!

**Comment by sebastianbergmann** [comment]
https://phpunit.de/announcements/ exists.

**Comment by jdufresne** [comment]
Thanks for the link. I'll try to remember that one as that page did not show up in my searching.

I still think it would be useful to also include this information as an appendix to the documentation.
