### ISSUE TITLE
Dutch (Netherlands) Documentation

### ISSUE THREAD

**Issue by oscodeproject** [sebastianbergmann/phpunit-documentation-english#184]
nl-NL | Dutch (Netherlands) documentation

**Comment by sebastianbergmann** [comment]
Do you want to translate the documentation to Dutch?

**Comment by oscodeproject** [comment]
Yes

**Comment by oscodeproject** [comment]
Did you create a repository where I can send the translate pull requests to?

**Comment by sebastianbergmann** [comment]
The PHPUnit project does not have the resources to coordinate the translation of the PHPUnit documentation into other languages. Some, if not most, of the existing translations have not been up-to-date with the English documentation for quite a while. I have therefore decided to no longer officially support documentation languages other than English.
