### ISSUE TITLE
assertContainsEquals is missing from documentation

### ISSUE THREAD

**Issue by mondrake** [sebastianbergmann/phpunit-documentation-english#190]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8+
| PHP version         | n/a
| Installation Method | n/a

#### Summary

sebastianbergmann/phpunit#3511 introduced the method `assertContainsEquals` as a follow up to `assertContains` refactoring, but AFAICS it's not documented in the official manual.

**Comment by alexekorn** [comment]
This tripped me up for a bit today. Nice that `assertContainsEquals()` exists (and it behaves exactly as I would expect), but strange that it isn't documented.

**Comment by sebastianbergmann** [comment]
This is now documented for PHPUnit >= 10. I do not think it's worth the effort to backport this to the documentation for PHPUnit < 10.
