### ISSUE TITLE
Naming convention of data provider methods

### ISSUE THREAD

**Issue by Kwadz** [sebastianbergmann/phpunit-documentation-english#194]
As we can see in the [data providers section](https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers) the data provider method is named `additionProvider`. Since a method should start with a verb, it's confusing. So, to avoid a bad practice in projects because of this example, I'd suggest renaming it to `provideAddition`.

If agreed, I'm ready to create a pull request.

**Comment by keradus** [comment]
there are some concrete patterns how to name providers used by some, eg `testFoo` -> `provideFooCases`

maybe the docs should try to not only avoid "bad practice", but share "best practice" (whatever it would be)

**Comment by sebastianbergmann** [comment]
I do not think that this should be covered in the documentation.
