### ISSUE TITLE
Add willReturnOnConsecutiveCalls to documentation

### ISSUE THREAD

**Issue by duncancumming** [sebastianbergmann/phpunit-documentation-english#20]
[This duplicates this ticket https://github.com/sebastianbergmann/phpunit-documentation/issues/488 which has been closed since the documentation was moved to separate projects per language]

In phpunit-mock-objects/src/Builder/InvocationMocker.php there's a willReturnOnConsecutiveCalls method, which isn't mentioned in the PHPUnit documentation. 
https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Builder/InvocationMocker.php#L173

Can we get that added please?

**Comment by plucht** [comment]
These shorthand methods aren't mentioned either: 

- `willReturnArgument()`
- `willReturnCallback()`
- `willReturnMap()`
- `willReturnSelf()`
- `willThrowException()`

Would it make sense to add a table to the page about test doubles, which compares these methods to their equivalents (e.g. `will($this->returnArgument(1))`)?

**Comment by SvenBrunk** [comment]
It's more than 3 years now... how about doing it? ;)

**Comment by seth-xdam** [comment]
This issue was resolved two years ago, but it the additional documentation was removed again two months ago in commit 2c6a4cd6a825a5e81e6263401f12e14431a20b17. The only comment on the commit is "Remove table". Why was the documentation on these additional functions deleted?

**Comment by terrylin104** [comment]
Probably it were deprecated in PHPUnit 12.
https://github.com/sebastianbergmann/phpunit/issues/5425
But I didn't see any @deprecated annotation in 10.3 or later version.
