### ISSUE TITLE
bug in PHPUnit Manual 9.5: Example 2.8 The CsvFileIterator class

### ISSUE THREAD

**Issue by ricfio** [sebastianbergmann/phpunit-documentation-english#220]
Bug:
[Example 2.8 The CsvFileIterator class](https://phpunit.readthedocs.io/en/9.5/writing-tests-for-phpunit.html#writing-tests-for-phpunit-data-providers-examples-csvfileiterator-php)

Fix:
https://github.com/ricfio/phpunit-tutorial/commit/cbc6059d776fa5cac7d670bf8301cb6c18ca4744

**Comment by sebastianbergmann** [comment]
I have no idea what you are trying to report. And a patch in an unrelated repository is not a fix.
