### ISSUE TITLE
Check occurrences of PHPUnit_

### ISSUE THREAD

**Issue by mhujer** [sebastianbergmann/phpunit-documentation-english#23]
While working on https://github.com/sebastianbergmann/phpunit-documentation-english/issues/3 I noticed that in the documentation there are many references to `PHPUnit_` classes which were already renamed.

They can be found by searching for `PHPUnit_` string in the IDE.

**Comment by keradus** [comment]
is there anything left here, after https://github.com/sebastianbergmann/phpunit/pull/2999 got merged ?

**Comment by mhujer** [comment]
https://github.com/sebastianbergmann/phpunit/pull/2999 resolved it only in the source code of the PHPUnit itself, but there are many more in the documentation.
