### ISSUE TITLE
Turkish Documentation

### ISSUE THREAD

**Issue by berkaycubuk** [sebastianbergmann/phpunit-documentation-english#231]
Hello Sebastian 👋

I'm a native Turkish speaker. To help people who speak Turkish, I want to translate the documentation to Turkish.

Thank you for your time.

Feel free to contact me: hey@berkaycubuk.com

**Comment by sebastianbergmann** [comment]
The PHPUnit project does not have the resources to coordinate the translation of the PHPUnit documentation into other languages. Some, if not most, of the existing translations have not been up-to-date with the English documentation for quite a while. I have therefore decided to no longer officially support documentation languages other than English.
