### ISSUE TITLE
A typo in 8. Test Doubles — Stubs

### ISSUE THREAD

**Issue by gleblobanov** [sebastianbergmann/phpunit-documentation-english#233]
Possibly a superfluous **to** in [8. Test Doubles — Stubs](https://phpunit.readthedocs.io/en/9.5/test-doubles.html#stubs):

> Example 8.2 shows how **to** stub method calls and set up return values.

**Comment by sebastianbergmann** [comment]
I do not think that this "to" is superfluous.
