### ISSUE TITLE
Docs are missing core feature from PHPUnit

### ISSUE THREAD

**Issue by crtl** [sebastianbergmann/phpunit-documentation-english#242]
There are many methods which are not documented or badly documented in the documentation.
For example I want to check out `tearDown` and `setUp` methods but there is no information in the documentation how and when theses methods actually run with usage examples.
The first contact you have is:
2, Data Providers (????)
> All data providers are executed before both the call to the setUpBeforeClass() static method and the first call to the setUp() method. Because of that you can’t access any variables you create there from within a data provider. This is required in order for PHPUnit to be able to compute the total number of tests.

This still doesnt explain this feature.
The first topic explicitly related to setUp and tearDown is `4. More setUp() than tearDown()`.
But whats more here? The feature wasn even explained to this point.
Also this topic does not include any information about the methods:
> setUp() and tearDown() are nicely symmetrical in theory, but not in practice. In practice, you only need to implement tearDown() if you have allocated external resources such as files or sockets in setUp(). If your setUp() just creates plain PHP objects, you can generally ignore tearDown().

I still dont know what it does and how to use it.

Also I want to test my traits so I use `getObjectForTrait` method but this is also missing from the website.

Where can I find this information?

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by crtl** [comment]
So you just keep the docs like this and all the features are just gone or how can I understand this?
