### ISSUE TITLE
Online document site not updated to the latest commit here

### ISSUE THREAD

**Issue by yookoala** [sebastianbergmann/phpunit-documentation-english#257]
In fc402cf (merged by 98d4621 in 29th Nov, 2021), the textui.rst was updated to reflect the latest command options. The change is not showing on the [live site](https://phpunit.readthedocs.io/en/9.5/textui.html#command-line-options) at the moment. Most notably, the `--coverage-cobertura` option is not there:

Documentation site right now:
|![2022-01-19 11-03-16 的螢幕擷圖](https://user-images.githubusercontent.com/91274/150056181-8e7f96a3-2cc9-4de1-9e14-2cb68ea19c80.png)|
|--|

The [source file](https://github.com/sebastianbergmann/phpunit-documentation-english/blob/ccf8ec818e78db69957054150a3f6dd4852e2fd6/src/textui.rst) of ccf8ec8 (the latest commit as of today, merged in 20th Dec, 2021):
|![2022-01-19 11-06-36 的螢幕擷圖](https://user-images.githubusercontent.com/91274/150056690-427b7639-f2fe-4d17-9815-805c0f65feea.png)|
|--|

Is there a specific merge / build window for the site to update to? Or is there, maybe, some problem with the automatic documentation site updating workflow?

**Comment by sebastianbergmann** [comment]
This has nothing to do with the build. In [its current state](https://github.com/sebastianbergmann/phpunit-documentation-english/blob/9.5/src/textui.rst), the `textui.rst` file does not have the content in question.

**Comment by yookoala** [comment]
The option exists in the current version (v9.5.11) of command tools. Is there any concern blocking the change going into v9.5 branch?

**Comment by sebastianbergmann** [comment]
No.

**Comment by yookoala** [comment]
Is there any way I can help to merge the change sooner?

**Comment by sebastianbergmann** [comment]
The change seems to have been lost somehow. I am sorry, but I do not have time to work on this right now.

**Comment by yookoala** [comment]
Understood. Please give some time to merge the change when you have time.

Thanks for your contribution over the years.
