### ISSUE TITLE
Test suite documentation should mention TestSuite objects

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit-documentation-english#260]
The docs at https://phpunit.readthedocs.io/en/9.5/organizing-tests.html#composing-a-test-suite-using-xml-configuration give an example of using the <file> tag in the XML configuration:

```
      <file>tests/IntlFormatterTest.php</file>
      <file>tests/MoneyTest.php</file>
      <file>tests/CurrencyTest.php</file>
```

The example code makes it look like things specified in the <file> tag are just test classes.

However, it looks like they can also be classes which extend PHPUnit\Framework\TestSuite and define the list of test classes in the suite. This should be documented too.

**Comment by sebastianbergmann** [comment]
`TestSuite` is not part of the public API and will eventually, hopefully soon, be removed. It should not be documented.

**Comment by joachim-n** [comment]
Thanks! I spotted it because Drupal uses it. I've filed an issue there to remove it: https://www.drupal.org/project/drupal/issues/3282051
