### ISSUE TITLE
Installing PHPUnit: broken link

### ISSUE THREAD

**Issue by alexislefebvre** [sebastianbergmann/phpunit-documentation-english#261]
On this section: https://phpunit.readthedocs.io/en/latest/installation.html#php-archive-phar

Or the `stable` branch: https://phpunit.readthedocs.io/en/stable/installation.html#php-archive-phar

There is a `curl` command to download the PHAR file.

But the links return a 404 code: https://phar.phpunit.de/phpunit-latest.phar and https://phar.phpunit.de/phpunit-stable.phar

The link works on the version 9: https://phpunit.readthedocs.io/en/9.5/installation.html#php-archive-phar

It may be an issue in with the `|version|` in this file: https://github.com/sebastianbergmann/phpunit-documentation-english/blob/9.5/src/installation.rst

Or you could add a symlinks from https://phar.phpunit.de/phpunit-latest.phar and https://phar.phpunit.de/phpunit-stable.phar to the latest version so that a PHAR file is returned.

**Comment by sebastianbergmann** [comment]
"latest", "stable", etc. should not have been visible.

**Comment by alexislefebvre** [comment]
- latest: that's right, I searched https://www.google.com/search?channel=fs&q=installing+PHPUnit and it returned me the French version, so I edited the URL manually to use `/en` but that wasn't the right way
- stable: this version is in the list of versions on bottom left on https://phpunit.readthedocs.io/en/9.5/installation.html which is a valid page from my understanding
