### ISSUE TITLE
Broken links “Edit on GitHub”

### ISSUE THREAD

**Issue by alexislefebvre** [sebastianbergmann/phpunit-documentation-english#262]
The link “Edit on GitHub” doesn't work on the following pages:

- https://phpunit.readthedocs.io/en/latest/installation.html
- https://phpunit.readthedocs.io/en/stable/installation.html
- https://phpunit.readthedocs.io/en/9.5/installation.html

Expected link: https://github.com/sebastianbergmann/phpunit-documentation-english/edit/9.5/src/installation.rst

Actual link: https://github.com/sebastianbergmann/phpunit-documentation-english//9.5/src/installation.rst

---

Old issues about this problem: https://github.com/sebastianbergmann/phpunit-documentation-english/search?q=Edit+on+GitHub&type=issues

**Comment by sebastianbergmann** [comment]
I cannot reproduce this. On `https://phpunit.readthedocs.io/en/9.5/installation.html` I see a link to `https://github.com/sebastianbergmann/phpunit-documentation-english/edit/9.5/src/installation.rst`.

**Comment by alexislefebvre** [comment]
Another other had this issue: https://github.com/sebastianbergmann/phpunit-documentation-english/issues/41#issuecomment-1135727758
