### ISSUE TITLE
Edit on GitHub links broken

### ISSUE THREAD

**Issue by jnoordsij** [sebastianbergmann/phpunit-documentation-english#268]
The "Edit on GitHub" links in the current version of the documentation, e.g. https://phpunit.readthedocs.io/en/10.0/, are broken.

The page above leads to https://github.com/sebastianbergmann/phpunit-documentation-english//10.0/src/index.rst, which should probably include 'blob': https://github.com/sebastianbergmann/phpunit-documentation-english/blob/10.0/src/index.rst.

**Comment by sebastianbergmann** [comment]
I do not know how to fix this, or if this is something we can fix or if this is an issue with ReadTheDocs itself.

**Comment by sebastianbergmann** [comment]
This seems to have been fixed by 9f931a501cee9dc2aa4c6ebb63979c86adbb1f44.
