### ISSUE TITLE
Feature request: add redirects on version bump

### ISSUE THREAD

**Issue by jnoordsij** [sebastianbergmann/phpunit-documentation-english#269]
With the recent release of PHPUnit 9.6 and 10.0, the 9.5 version of the docs are no longer available, and all 9.5-versioned links will result in a 404. However, most search engines still have the 9.5 version indexed, which leads to a huge number of dead links when using search engines to look up the documentation, which is a bit user unfriendly.

I think it would a useful thing to have some automatic redirect on version bumps, which helps both real-life users and also helps search engines to update their links faster.

**Comment by sebastianbergmann** [comment]
I have reactivated the PHPUnit 9.5 documentation. However, PHPUnit 9.5 is superseded by PHPUnit 9.6 and I do not think it makes sense to continue offering documentation for PHPUnit 9.5.

**Comment by jnoordsij** [comment]
Thanks! 

I do agree it makes sense to take it offline at some point, hopefully most search engines will pick up the new version soon enough. But a grace period might be a suitable solution.
