### ISSUE TITLE
Test Doubles chapter not quite correct regarding static methods 

### ISSUE THREAD

**Issue by chrisminett** [sebastianbergmann/phpunit-documentation-english#27]
Ported issue by @llernestal from archived phpunit-documentation repo:
https://github.com/sebastianbergmann/phpunit-documentation/issues/395

-----

The documentation says:

> Please note that `final`, `private` and `static` methods cannot be stubbed or mocked. They are ignored by PHPUnit's test double functionality and retain their original behavior.

But `static` methods DO NOT retain their original behavior. The method body is replaced with:

```php
throw new PHPUnit_Framework_MockObject_BadMethodCallException('Static method "{method_name}" cannot be invoked on mock object');
```

Maybe the documentation should say something about that?

### Code reference

```php
        if ($static) {
            $templateFile = 'mocked_static_method.tpl';
        } else {
```

https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Generator.php#L995-L997

```php
    {modifier} function {reference}{method_name}({arguments_decl}){return_delim}{return_type}
    {
        throw new \PHPUnit\Framework\MockObject\BadMethodCallException('Static method "{method_name}" cannot be invoked on mock object');
    }
```

https://github.com/sebastianbergmann/phpunit-mock-objects/blob/master/src/Generator/mocked_static_method.tpl.dist

**Comment by gbprod** [comment]
I think we can close this issue ?

**Comment by clns** [comment]
So you cannot call static methods in tests? I have a few tests that fail because of this, but I am not sure what the solution would be.
