### ISSUE TITLE
Japanase Documentation is closed.

### ISSUE THREAD

**Issue by kuromoka** [sebastianbergmann/phpunit-documentation-english#271]
Hi, I was a contributor to phpunit-documentation-japanese.
I understand to no longer officially support documentation languages other than English, but I was't expect to close the site too.

I folk the repository and want to continue translating.
If so, Is it difficult to revive the same URL (http://phpunit.readthedocs.io/ja/latest/)? or can I set up an unofficial document site?

**Comment by sebastianbergmann** [comment]
You are free to host an unofficial translation of PHPUnit's doumentation anywhere you like.

**Comment by kuromoka** [comment]
appriciate very quick reply
