### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by BSarmady** [sebastianbergmann/phpunit-documentation-english#288]
Reading following document page to understand XML configuration file format.

https://docs.phpunit.de/en/10.0/configuration.html

I'm interested in specific elements such as `pathCoverage`, `include`, `phpVersion` and `report`

Looking at document I cannot find where each element supposed to go? is it enough to just drop it in XML file anywhere I like or need to put it in specific order and specific parent node?

**Comment by sebastianbergmann** [comment]
Look at the structure of the document, for instance:

- The `<coverage>` Element (first line of this section: "Parent element: `<phpunit>`")
  -  The `pathCoverage` Attribute

This should make it clear that the `<coverage>` element is a child of `<phpunit>` and that `pathCoverage` is an attribute of `<coverage>`.

I highly recommend editing PHPUnit's XML configuration with an IDE such as PhpStorm which uses the [schema definition](https://schema.phpunit.de/10.0/phpunit.xsd) to support you with auto-complete and on-the-fly validation.
