### ISSUE TITLE
Use assertSame() instead of assertEquals() where possible

### ISSUE THREAD

**Issue by mhujer** [sebastianbergmann/phpunit-documentation-english#3]
> Repost of https://github.com/sebastianbergmann/phpunit-documentation/issues/494.

-----

I noticed that the [introductory documentation chapter](https://phpunit.readthedocs.io/en/latest/writing-tests-for-phpunit.html) uses `assertEquals()`. I suggest that it can be replaced with `assertSame()`, which is stricter a may prevent unexpected type conversion bugs.

What do you think?

If you think it is a good idea, I can prepare a PR.

**Comment by keradus** [comment]
big :+1:

**Comment by sebastianbergmann** [comment]
Go for it.

**Comment by mhujer** [comment]
I started changing the documentation, but when I was testing the example output I ran into an issue with the array not being diffed when `assertSame` is used.

See the example [from docs](https://phpunit.readthedocs.io/en/latest/writing-tests-for-phpunit.html#error-output):
```php
<?php
use PHPUnit\Framework\TestCase;

class ArrayDiffTest extends TestCase
{
    public function testEquality() {
        $this->assertEquals(
            [1, 2,  3, 4, 5, 6],
            [1, 2, 33, 4, 5, 6]
        );
    }
}
```

It outputs this, so you can easily tell what's the problem:
```
1) ArrayDiffTest::testEquality
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 1
     1 => 2
-    2 => 3
+    2 => 33
```


But when the `assertEquals()` is replaced with `assertSame()`, the output is the following, which is pretty hard to digest.
```
2) ArrayDiffTest::testEquality2             
Failed asserting that Array &0 (            
    0 => 1                                  
    1 => 2                                  
    2 => 33                                 
    3 => 4                                  
    4 => 5                                  
    5 => 6                                  
) is identical to Array &0 (                
    0 => 1                                  
    1 => 2                                  
    2 => 3                                  
    3 => 4                                  
    4 => 5                                  
    5 => 6                                  
). 
```

There is already an issue describing this https://github.com/sebastianbergmann/phpunit/issues/2169 (and the older one https://github.com/sebastianbergmann/phpunit/issues/1252). 

I will try to have a look at the diffing issue first, because it would be hard to persuade users to use a stricter assert, if it provides worse DX.
