### ISSUE TITLE
Clarification of cacheResult "other features"

### ISSUE THREAD

**Issue by adamcameron** [sebastianbergmann/phpunit-documentation-english#306]
Hi
Firstly: thanks for everything. This is just a minor observation.

Could we poss have some elaboration in the guidance for `cacheResult` (https://docs.phpunit.de/en/10.1/configuration.html#the-cacheresult-attribute):

> This caching is required for certain other features to work.

Which ones?

I had a shufti around the rest of the docs, but that's the only mention of "cacheResult".

Cheers!

**Comment by localheinz** [comment]
Thank you for reporting, @adamcameron - while investigating, I spotted a bug and fixed it, too - see https://github.com/sebastianbergmann/phpunit/pull/5348.

**Comment by localheinz** [comment]
Fixed with #5348.
