### ISSUE TITLE
Is it clear to reader when to create the greeter.php file?

### ISSUE THREAD

**Issue by carlhunterroach** [sebastianbergmann/phpunit-documentation-english#319]
First-time user of this documentation and PHPUnit.

I created `GreeterTest.php` but when I run it, it doesn't find `src/Greeter.php` because I haven't created/added it.
Have I missed the instruction or is the instruction missing to create `src/Greeter.php`?

To reproduce:
Follow the `composer` sections of [installation](https://docs.phpunit.de/en/10.2/installation.html)
And then start [writing a test](https://docs.phpunit.de/en/10.2/writing-tests-for-phpunit.html#).

**Comment by sebastianbergmann** [comment]
Thank you for your valuable feedback!
