### ISSUE TITLE
[Feedback wanted] Contribution ideas

### ISSUE THREAD

**Issue by two-plus-two-equals-five** [sebastianbergmann/phpunit-documentation-english#331]
Hey @sebastianbergmann and co.

I wanted to see if the following two contribution ideas for this repo would be wanted / welcomed:
<ol type="A">
  <li>
      <p>
      Supply a Dockerfile in the repo to:
      </p>
      <ul>
          <li>
               <p>
               handle keeping <i>all</i> of the Python and Sphinx dependencies automatically up-to-date without requiring contributors to manually install these dependencies themselves on their machines
               </p>
          </il>
          <li>
               <p>
               remove the need to supply and update a `/tools` directory (instead leveraging packages like `composer` to handle this via a PHP base Docker image)
              </p>
          </li>
      </ul>
  </li>
  <li>
   <p> 
     Build a deployment pipeline for this repo to:
    </p>
     <ol type='1'>
        <li>
           <p>
           automatically pull the latest stable release of PHPUnit the instant it's out (or whenever a still-supported version is updated)
           </p>
        </li>
        <li>
           <p>
           then automatically run the assertion output generator script + the HTML documentation script (`make html`) - having a Dockerfile to set up these scripts' dependencies would aid with this
           </p>
        </li>
        <li>
           then either:
               <ol type='a'>
                    <li>
                      <p>
                       upload the generated HTML files somewhere to some hosting server to be propagated to the "production" 'Read the doc' documentation site once it has been manually approved, or
                      </p>
                    </li>
                    <li>
                       <p>
                       just dump the generated files out to your local machine for viewing + manual propagation.
                       </p>
                    </li>
               </ol>
        </li>
     </ol>
  </li>
</ol>  

</br>

  
<p>
Reasons behind the suggestions above: reducing manual tasks reduces the chances of documentation going stale + makes contributions more straightforward todo as there is an improved development experience (reducing the number of things for contributors to do and get right in order to make a contribution).
</p>

</br>

Side question:
* What is the process for propagating the generated HTML files to the 'Read the docs' site?

</br>
</br>

I hope the above is useful, but if not, then no worries!

**Comment by sebastianbergmann** [comment]
> 1. Supply a Dockerfile in the repo to:
>              
>              
>                  * handle keeping all of the Python and Sphinx dependencies automatically up-to-date without requiring contributors to manually install these dependencies themselves on their machines* remove the need to supply and update a `/tools` directory (instead leveraging packages like `composer` to handle this via a PHP base Docker image)

I am not interested in this.

> 2. Build a deployment pipeline for this repo to:

We already have this (just not as a GitHub Action): the documentation is built and deployed after each push.
