### ISSUE TITLE
Priority for hook methods

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-documentation-english#364]
Follows https://github.com/sebastianbergmann/phpunit/pull/5890.

**Comment by nikophil** [comment]
Hi!

I wanted to document this feature, but I'm not sure where to put this.

Do you think a whole paragraph `Template methods priority` with its entry in the TOC is needed? Or add a small paragraph for each attribute is enough?

**Comment by sebastianbergmann** [comment]
I will take care of this.
