### ISSUE TITLE
Links to documentation broken on each minor release

### ISSUE THREAD

**Issue by martinssipenko** [sebastianbergmann/phpunit-documentation-english#386]
Hello,

I'm wondering if it would be possible to fix breaking of documentation links that occur on each major/minor version. Right now as minor version is released the documentation links change from e.g. `https://docs.phpunit.de/en/11.4/configuration.html` to `https://docs.phpunit.de/en/11.5/configuration.html`, while I assume the versions are backward compatible and the documentation would still be applicable. Perhaps this could be fixed by using `11.x` as branch names so that links would remain the same across minor versions?

**Comment by sebastianbergmann** [comment]
We unpublish documentation for branches that are no longer supported. For example, the support for PHPUnit 11.4 ended with the release of PHPUnit 11.5.

As PHPUnit 11.5 is backward compatible with PHPUnit 11.4, there is no reason for not updating to PHPUnit 11.5 and therefore no reason to keep the documentation for PHPUnit 11.4.

**Comment by sebastianbergmann** [comment]
I have recreated the `11.0`, `11.1`, `11.2`, `11.3`, `11.4` branches and have reactivated their builds on `docs.phpunit.de`. They should become available there again soon. Do not though that they are hidden from the navigation.

I will try to recreate and reactivate the `10.0`, `10.1`, `10.2`, `11.0`, `10.4` branches as soon as possible. I will not go further back in time then that, though.

**Comment by martinssipenko** [comment]
Thank you very much!

I agree that everyone should update to latest minor version as soon as it comes out as it is backward compatible, and I think many do, I know I do, but the update is often somewhat invisible. I often have `^11.0` in my composer file and update to latest version happens via Dependabot or just running `composer update`. However, I also have places in configuration where links to official docs are added as comments, and on each minor version the links broke. IMO best case scenario would be that links to major version would be static and would not change with each minor, this way links would always point to latest version of documentation for given major version.
