### ISSUE TITLE
All URLs to `current` are broken (as found via Google Search)

### ISSUE THREAD

**Issue by citricsquid** [sebastianbergmann/phpunit-documentation-english#39]
e.g: https://phpunit.de/manual/current/en/test-doubles.html

**Comment by sebastianbergmann** [comment]
`current` is no longer current and therefore no longer exists.

**Comment by citricsquid** [comment]
@sebastianbergmann This breaks so many search engine results as Google prioritises the `current` page in results instead of specific versions. This also breaks developers bookmarks, and references made in code comments, stackoverflow posts, GitHub issues...

Although I understand that you've moved the documentation elsewhere, it would be very helpful if the old links at the very least displayed an error message directing the user to the new documentation location, or ideally a redirect to the new documentation location.

This stackoverflow question depends heavily on these links and has 40,000 views alone: https://stackoverflow.com/questions/10254180/difference-between-assertequals-and-assertsame-in-phpunit

**Comment by citricsquid** [comment]
A possible middle ground approach is using the readthedocs.io's search feature, as it appears to work fairly well for this. You could have a single redirect, which would be:

```
https://phpunit.de/manual/current/en/{file}.html -> https://phpunit.readthedocs.io/en/7.1/search.html?q={file}
```

For example: http://phpunit.readthedocs.io/en/latest/test-doubles.html would redirect to https://phpunit.readthedocs.io/en/7.1/search.html?q=test-doubles

**Comment by sebastianbergmann** [comment]
I do not like the idea expressed in https://github.com/sebastianbergmann/phpunit-documentation-english/issues/39#issuecomment-380142307 because it bypasses the information provided on https://phpunit.de/documentation.html.

**Comment by sebastianbergmann** [comment]
Before the `current` "symlink" was removed, `https://phpunit.de/manual/current/en/test-doubles.html`, for instance, was the same as `https://phpunit.de/manual/6.5/en/test-doubles.html`.

Therefore, requests to `https://phpunit.de/manual/current/en/test-doubles.html` are now redirected to `https://phpunit.de/manual/6.5/en/test-doubles.html`.

Yes, this contradicts what I wrote in https://github.com/sebastianbergmann/phpunit-documentation-english/issues/39#issuecomment-380143266. But I realized that I do not want to break the expectation to find the content you're looking for when you follow a link.
