### ISSUE TITLE
The "Edit on GitHub" links do not work on Read the Docs for es, fr, pt, ja and zh languages

### ISSUE THREAD

**Issue by dzc34** [sebastianbergmann/phpunit-documentation-english#41]
The "_Edit on GitHub_" links do not work on Read the Docs for es, fr, pt, ja and zh languages

ex:
https://phpunit.readthedocs.io/ja/latest/
![](https://user-images.githubusercontent.com/6709977/38953860-56a3ecf0-4350-11e8-8e6c-9e8f0350496f.png)
`https://github.com/sebastianbergmann/phpunit-documentation-japanese//master/src/index.rst`

**Comment by sebastianbergmann** [comment]
I am not sure what I can/should do about this. @belanur?

**Comment by belanur** [comment]
This is also the case for the English master version (which is hidden to regular users): http://phpunit.readthedocs.io/en/master/

It seems the link works with versions that are based on branches as tags, so I would assume that configuring the translations the same way as the English documentation would lead to working links. This is how the setup looks like on readthedocs.org:
<img width="575" alt="screenshot 2018-04-19 09 58 57" src="https://user-images.githubusercontent.com/169095/38978668-575b2ba0-43b8-11e8-8817-8ac15d9c8969.png">

**Comment by keradus** [comment]
```diff
-https://github.com/sebastianbergmann/phpunit-documentation-japanese//master/src/index.rst
+https://github.com/sebastianbergmann/phpunit-documentation-japanese/blob/master/src/index.rst
```

(see missing `blob`)

**Comment by sebastianbergmann** [comment]
Sorry, but I am still not sure what I should do about this.

Do I understand correctly, @belanur, that I need to change the ReadTheDocs configuration and that this is a one-time change and not something that needs to be done every time there is a new branch?

Besides that, I would like to have the translation teams create/maintain the version-specific branches. I will do that for the English edition.

**Comment by joachim-n** [comment]
The edit link on the English version is still broken.

E.g. at https://phpunit.readthedocs.io/en/9.5/organizing-tests.html the link is https://github.com/sebastianbergmann/phpunit-documentation-english//9.5/src/organizing-tests.rst which is a 404.

**Comment by sebastianbergmann** [comment]
The PHPUnit project does not have the resources to coordinate the translation of the PHPUnit documentation into other languages. Some, if not most, of the existing translations have not been up-to-date with the English documentation for quite a while. I have therefore decided to no longer officially support documentation languages other than English.
