### ISSUE TITLE
Missing documentation for @requires comparison operators

### ISSUE THREAD

**Issue by johnbillion** [sebastianbergmann/phpunit-documentation-english#44]
The [documentation for the `@requires` annotation](https://phpunit.readthedocs.io/en/7.1/incomplete-and-skipped-tests.html#skipping-tests-using-requires) makes no mention of comparison operators.

Comparison operator support was added in PHPUnit 5.2. See https://github.com/sebastianbergmann/phpunit/issues/1984.

**Comment by NathanGibbs3** [comment]
This definitely needs to be documented.
I've been using `version_compare` in my unit tests because I thought @require was a hard `==` logical operation with no flexibility.

**Comment by NathanGibbs3** [comment]
Beautiful :exclamation: 
Thank You. :smile: :+1:
