### ISSUE TITLE
documentation for expectException() should say that it will catch multiple exceptions

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit-documentation-english#47]
If a test does this:

```
    public function testException()
    {
        $this->expectException(\Exception::class);
        
        throw new \Exception;

        throw new \Exception;

    }
```

then a developer might expect that expectException() will handle the first thrown exception, and fail the second one.

That is not however the case: both exceptions (and presumably an unlimited number) are handled.

The documentation should mention this.

**Comment by keradus** [comment]
both exceptions are not handled by `expectException`. `expectException` handle first exception that is thrown, as after that - second exception is not thrown at all, as the execution was interrupted already.

```php
throw new \Exception();
echo 123;                // <-- this never happens!
throw new Exception ();  // <-- so this can't be handled at all
```

**Comment by joachim-n** [comment]
Ok, so can the documentation say *that* instead?

In other words, that expectException() necessarily ends a test.

**Comment by keradus** [comment]
it's not about `expectException`. it's about how throwing exceptions work in languages.
`expectException` doesn't end a test, Exception that is thrown does.
