### ISSUE TITLE
--configuration option with directory argument not documented

### ISSUE THREAD

**Issue by siliconforks** [sebastianbergmann/phpunit-documentation-english#5]
In https://phpunit.de/manual/5.4/en/textui.html#textui.clioptions it states that the `--configuration` option takes a "file" as an argument, but it does not mention anywhere that a directory may also be used.

\[Note: this was migrated from sebastianbergmann/phpunit-documentation#352 - it appears that the latest documentation at https://phpunit.readthedocs.io/en/latest/textui.html still has the issue.\]

**Comment by keradus** [comment]
#17 got merged, please close this issue
