### ISSUE TITLE
Removing the closing PHP tags from the examples

### ISSUE THREAD

**Issue by lex111** [sebastianbergmann/phpunit-documentation-english#56]
How about to slightly simplify the code examples, and remove the closing PHP tags, and maybe even opening PHP tags?

```php
<?php
use PHPUnit\Framework\TestCase;

class ContainsTest extends TestCase
{
    public function testFailure()
    {
        $this->assertContains('baz', 'foobar');
    }
}
?>
```

The example above will look like this:

```php
use PHPUnit\Framework\TestCase;

class ContainsTest extends TestCase
{
    public function testFailure()
    {
        $this->assertContains('baz', 'foobar');
    }
}
```

Or even remove the closing tags, because it is customary to omit them. What do you think, @sebastianbergmann?

**Comment by sebastianbergmann** [comment]
I'm all for removing the closing tags.
