### ISSUE TITLE
Add willReturnOnConsecutiveCalls to documentation

### ISSUE THREAD

**Issue by duncancumming** [sebastianbergmann/phpunit-documentation-english#6]
[This duplicates this ticket https://github.com/sebastianbergmann/phpunit-documentation/issues/488 which has been closed since the documentation was moved to separate projects per language]

In phpunit-mock-objects/src/Builder/InvocationMocker.php there's a willReturnOnConsecutiveCalls method, which isn't mentioned in the PHPUnit documentation. Can we get that added please?

**Comment by reinholdfuereder** [comment]
This issue is duplicated by #20: however, since the latter has an additional comment, I would opt for resolving/closing this issue here...
