### ISSUE TITLE
Simplify the contents of the Constraints table

### ISSUE THREAD

**Issue by lex111** [sebastianbergmann/phpunit-documentation-english#64]
I suggest removing the substring "_it is evaluated for_" from [the following table](https://phpunit.readthedocs.io/en/latest/assertions.html#appendixes-assertions-assertthat-tables-constraints), because it complicates the general sentence.

Is it not better, compare:

| Before | After
| - | -
| Constraint that asserts that the value it is evaluated for is greater than a given value. | Constraint that asserts that the value is greater than a given value.

Currently some lines of this table do not contain this substring (_Constraint that accepts any input value._)

@sebastianbergmann what do you think about this?

**Comment by sebastianbergmann** [comment]
Makes sense.

**Comment by keradus** [comment]
#65 is merged already, this issue shall be closed


I assume that you are doing cherry picking instead of regular merges @sebastianbergmann ? for that, github won't automatically close issues for you

**Comment by keradus** [comment]
it was merged to 7.1 branch, while main branch is master.
ticket would be autoclosed only if info about merge to 7.1 would remain in merge of 7.1 into master
