### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by lex111** [sebastianbergmann/phpunit-documentation-english#67]
When was the last time the documentation on https://phpunit.readthedocs.io was updated?

New changes, which are currently in the repository, there are no in that online documentation.

cc @sebastianbergmann

**Comment by lex111** [comment]
Strange, but it's not.

Here on [this page](https://phpunit.readthedocs.io/en/7.1/writing-tests-for-phpunit.html), assertEquals should be "highlighted", but the documentation does not.

See for yourself:

![image](https://user-images.githubusercontent.com/4408379/40741116-42fd283c-6453-11e8-8044-9b14a7209ff0.png)

![image](https://user-images.githubusercontent.com/4408379/40741132-52c03624-6453-11e8-9d56-bb298666c9a4.png)

**Comment by dzc34** [comment]
The 7.1 branch is often merged into the master branch. All commits of branch 7.1 in the master branch. But some commits of the master branch are not in the 7.1 branch.

Diff:
  - [/master/src/writing-tests-for-phpunit.rst](https://github.com/sebastianbergmann/phpunit-documentation-english/blame/master/src/writing-tests-for-phpunit.rst#L1060)
  - [/7.1/src/writing-tests-for-phpunit.rst](https://github.com/sebastianbergmann/phpunit-documentation-english/blame/7.1/src/writing-tests-for-phpunit.rst#L1060)

**Comment by dzc34** [comment]
Maybe, you should only accept PR on 1 branch (ex: master) and merge regularly in the other branch (ex: 7.1). Or, use only one branch for the latest version (7.1) and configure it to be the default branch in github.
