### ISSUE TITLE
Document getObjectForTrait()

### ISSUE THREAD

**Issue by duncancumming** [sebastianbergmann/phpunit-documentation-english#8]
[This duplicates this ticket https://github.com/sebastianbergmann/phpunit-documentation/issues/345 which has been closed since the documentation was moved to separate projects per language]

There's no mention of  the getObjectForTrait method in the documentation.

There was a blog article mentioning this method from 2011 https://sebastian-bergmann.de/archives/906-Testing-Traits.html but that seems to have vanished. 

The undocumented code is in phpunit/src/Framework/TestCase.php

**Comment by sebastianbergmann** [comment]
The `getObjectForTrait()` method is [deprecated](https://github.com/sebastianbergmann/phpunit/issues/5244). Documenting it now is likely pointless.
