### ISSUE TITLE
Russian translation is ready

### ISSUE THREAD

**Issue by lex111** [sebastianbergmann/phpunit-documentation-english#84]
Hi @sebastianbergmann 

I translated this documentation into Russian, the repository is available at this [link](https://github.com/php-ru/phpunit-documentation-russian).

I understand, now I have to transfer you this repository? Do I still have access to it?

And another question that is interesting to me - why not create an organization on GitHub for official repositories that are related to PHPUnit, why this was not done before? For example, here https://github.com/phpspec

**Comment by lex111** [comment]
I understood, but what about this?

> And another question that is interesting to me - why not create an organization on GitHub for official repositories that are related to PHPUnit, why this was not done before? For example, here @phpspec

**Comment by lex111** [comment]
I still care about this question, but I transfer the repository to you, please make all the necessary preparations (including publish a link to the Russian translation on the official website).

**Comment by lex111** [comment]
@sebastianbergmann you did not get my repository? I transfered it to you.

**Comment by sebastianbergmann** [comment]
My apologies for not immediately accepting the transfer, now it has expired. Please send a new transfer. Thanks!

**Comment by lex111** [comment]
Transfer again. Please do everything necessary to have Russian documentation (including the link on the site) as soon as possible.
