### ISSUE TITLE
mapTestClassNameToCoveredClassName is present in the documentation

### ISSUE THREAD

**Issue by AylanBoscarino** [sebastianbergmann/phpunit-documentation-english#91]
According to this issue https://github.com/sebastianbergmann/phpunit/issues/1936 the feature mapTestClassNameToCoveredClassName has been removed, however it's still present in the documentation in the XML Configuration File but without an explanation: https://phpunit.readthedocs.io/en/7.3/configuration.html#phpunit.
So is it working or is the documentation outdated?

**Comment by OndraM** [comment]
Solved in https://github.com/sebastianbergmann/phpunit-documentation-english/commit/b3de9fab4fc49be908100a9485ba39eaf7a88ff4

**Comment by b-hayes** [comment]
Looks like its still there, I came here looking for what it does.
