### ISSUE TITLE
Misleading documentation about doubles

### ISSUE THREAD

**Issue by dneprovec** [sebastianbergmann/phpunit-documentation-english#92]
Hello.
In the [documentation](https://phpunit.readthedocs.io/en/7.3/test-doubles.html) about test doubles we can read:

> > Limitation: final, private, and static methods

> 
> Please note that final, private, **_protected_**, and static methods cannot be stubbed or mocked.

In the body of this limitation block **_protected_** method is mentioned though it is not correct because it is possible to create a stub for protected method

**Comment by keradus** [comment]
nice catch @dneprovec , can you submit a PR to fix that, please ? :)
